language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
branches:
  only:
    - master
#Travis CI 서버 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
#clean 후 Build(Build시 자동으로 test 수행)
script: "./gradlew clean build"

after_success:
  - ./gradlew cobertura coveralls